# Generated by Django 4.2.4 on 2023-08-25 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='type',
            new_name='tipo',
        ),
    ]
